language: ruby
rvm:
- 2.1.5
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/

deploy:
  provider: heroku
  api_key:
    secure: kW1J96BXIIsH8KHp/qCkiIsEBrWE3KnT98Ijx4bDqLO4YwWBhkMEZKcIDebhtN3v8DeBbX1LFYagCLsdhqoC5NIxVHPNHajHUyLNrJS8Av21f3fNlJVVa6XtVfk2vAk9pI/f1Xzx5o8pb3CuqnmNGiiGL0ebrfz/7G+AfBKBFAZAQ4wDzh1D1PkHt+HFBItFzTRO2+641SI5osMpAc9V09fZCUGMgR0YDlYzw6+HYW6c8RSz4oJne6Y+jMqLhTvf+tp64AR0q9t/zpUIGRjjIT2CXexeMwDUcB01XhWbXtckOJvSPu06SBimhZ0s88oAlpSrRkFV+iCJ0xAdinFj8nK7EO9gh4CDxX+xMj151WgE1aHcexm/d/6LJ9R5TQ+ndjNLDs203kDPbp5YIfOwSrBEcYMXm0vcymdpdcy1jJkLEea6dXB9czOhVSzuNPKF8SAheiXcAO1XBz38CTe8prJgEdJmrAm8LA7pmQBgIVfTjMhQcuplFDOMSAxE06MOzwYPghyblJCpGLMjTaWVxCZy2Zk116ran2fDuHU8ZeFkXZRKEX5FKrB3KMqKhz0p7dVwcRMHpwP+BbmIfMaRExpLuHgWs8TSWVxdWXbBxOXNFgM0rxKKmheIPYivEQIy50XA4sSvcQzNyS0tEk85tNUxOIJ5ccgi5onzn0bFFDM=
  app: ratebeer
  on:
    repo: 7rxyk/RubyOnRails
    run: rake db:migrate
